import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, unlinkSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import { CONFIG_DIR, INSTANCE_URL } from "../config.js";

export const SCRIPT_PATH = join(CONFIG_DIR, "auto-push.sh");
export const LOG_PATH = join(CONFIG_DIR, "auto-push.log");
const PLIST_PATH = join(homedir(), "Library", "LaunchAgents", "com.tokenmax.push.plist");
const CRON_TAG = "# tokenmax auto-push";
const LABEL = "com.tokenmax.push";
/**
 * Fixed hours rather than an interval, so every machine lands on the same
 * boundaries and a reinstall does not shift the phase. A push covers everything
 * since the last one, so a skipped tick costs nothing but lag.
 */
const HOURS = [0, 6, 12, 18];
/** Said once here so the CLI never disagrees with the schedule it installed. */
export const SCHEDULE_LABEL = "every 6 hours";

export type Scheduler = "launchd" | "cron";

export function schedulerFor(platform = process.platform): Scheduler | null {
  if (platform === "darwin") return "launchd";
  if (platform === "linux") return "cron";
  return null;
}

/**
 * A tiny wrapper the schedule points at.
 *
 * launchd and cron run with a near-empty PATH — no Homebrew, no nvm, often no
 * node at all — so the interpreter is resolved now, while a real shell is
 * available, and written in absolutely. A bare `npx` here is why nothing ran.
 */
function script(): string {
  const nodeDir = dirname(process.execPath);
  const path = [nodeDir, "/opt/homebrew/bin", "/usr/local/bin", "/usr/bin", "/bin"].join(":");

  return [
    "#!/bin/sh",
    "# Generated by tokenmax. Remove with: tokenmax auto --off",
    `export PATH="${path}:$PATH"`,
    `export TOKENMAX_API_URL="\${TOKENMAX_API_URL:-${INSTANCE_URL}}"`,
    `echo "--- $(date) ---" >> "${LOG_PATH}"`,
    `exec "${process.execPath}" "${npxPath(nodeDir)}" -y github:ultim8xyz/tokenmax-cli push >> "${LOG_PATH}" 2>&1`,
    "",
  ].join("\n");
}

function writeScript(): void {
  if (!existsSync(CONFIG_DIR)) mkdirSync(CONFIG_DIR, { recursive: true, mode: 0o700 });
  writeFileSync(SCRIPT_PATH, script(), { encoding: "utf-8", mode: 0o700 });
}

/** npm ships npx beside node; falling back to the name lets PATH try. */
function npxPath(nodeDir: string): string {
  const candidate = join(nodeDir, "npx-cli.js");
  return existsSync(candidate) ? candidate : join(nodeDir, "npx");
}

/**
 * `RunAtLoad` is what covers a machine that was off: launchd loads agents at
 * login, so a laptop that missed every tick overnight pushes as soon as someone
 * signs in. launchd also runs a calendar job it slept through, on wake.
 */
function plist(): string {
  const calendar = HOURS.map(
    (h) => `    <dict><key>Hour</key><integer>${h}</integer><key>Minute</key><integer>0</integer></dict>`,
  ).join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>${LABEL}</string>
  <key>ProgramArguments</key>
  <array><string>/bin/sh</string><string>${SCRIPT_PATH}</string></array>
  <key>StartCalendarInterval</key>
  <array>
${calendar}
  </array>
  <key>RunAtLoad</key><true/>
</dict>
</plist>
`;
}

function crontab(lines: string): void {
  execFileSync("crontab", ["-"], { input: lines, encoding: "utf-8" });
}

function readCrontab(): string {
  try {
    return execFileSync("crontab", ["-l"], { encoding: "utf-8", stdio: ["ignore", "pipe", "ignore"] });
  } catch {
    return "";
  }
}

export function isInstalled(): boolean {
  const scheduler = schedulerFor();
  if (scheduler === "launchd") return existsSync(PLIST_PATH);
  if (scheduler === "cron") return readCrontab().includes(CRON_TAG);
  return false;
}

/**
 * Installs the recurring push, overwriting any earlier one — re-running this is
 * how a machine picks up a changed schedule.
 *
 * Returns null when the platform has no scheduler.
 */
export function install(): Scheduler | null {
  const scheduler = schedulerFor();
  if (!scheduler) return null;
  writeScript();

  if (scheduler === "launchd") {
    mkdirSync(join(homedir(), "Library", "LaunchAgents"), { recursive: true });
    writeFileSync(PLIST_PATH, plist(), "utf-8");
    // Reloading is what makes a changed schedule take effect; a plain load on
    // an already-loaded label is a no-op that looks like success.
    try {
      execFileSync("launchctl", ["unload", PLIST_PATH], { stdio: "ignore" });
    } catch {
      // Not loaded yet, which is the normal first install.
    }
    execFileSync("launchctl", ["load", PLIST_PATH], { stdio: "ignore" });
    return "launchd";
  }

  const existing = readCrontab()
    .split("\n")
    .filter((l) => l && !l.includes(CRON_TAG));
  // cron, unlike launchd, drops a tick it slept through — @reboot is the catch-up.
  crontab(
    [
      ...existing,
      `0 ${HOURS.join(",")} * * * /bin/sh ${SCRIPT_PATH} ${CRON_TAG}`,
      `@reboot /bin/sh ${SCRIPT_PATH} ${CRON_TAG}`,
      "",
    ].join("\n"),
  );
  return "cron";
}

/**
 * True when what is on disk is not what this version would write.
 *
 * The CLI itself updates on every run — the wrapper re-resolves
 * `github:ultim8xyz/tokenmax-cli` from the network each time — but the wrapper
 * and the schedule around it are generated once at install and would otherwise
 * stay frozen at whatever version created them. Comparing the generated text is
 * what lets a changed schedule, or a node that moved, reach a machine nobody
 * runs a command on.
 */
export function isStale(): boolean {
  if (!isInstalled()) return false;

  const current = (file: string): string | null => {
    try {
      return readFileSync(file, "utf-8");
    } catch {
      return null;
    }
  };

  if (current(SCRIPT_PATH) !== script()) return true;
  if (schedulerFor() === "launchd") return current(PLIST_PATH) !== plist();
  return !readCrontab().includes(`0 ${HOURS.join(",")} * * * /bin/sh ${SCRIPT_PATH} ${CRON_TAG}`);
}

/** Reinstalls when stale. Returns whether it did. */
export function refresh(): boolean {
  if (!isStale()) return false;
  install();
  return true;
}

export function uninstall(): void {
  const scheduler = schedulerFor();
  if (scheduler === "launchd" && existsSync(PLIST_PATH)) {
    try {
      execFileSync("launchctl", ["unload", PLIST_PATH], { stdio: "ignore" });
    } catch {
      // Already unloaded.
    }
    unlinkSync(PLIST_PATH);
  }
  if (scheduler === "cron") {
    const kept = readCrontab()
      .split("\n")
      .filter((l) => l && !l.includes(CRON_TAG));
    crontab([...kept, ""].join("\n"));
  }
  if (existsSync(SCRIPT_PATH)) unlinkSync(SCRIPT_PATH);
}
