import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, unlinkSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import { CONFIG_DIR, INSTANCE_URL } from "../config.js";

export const SCRIPT_PATH = join(CONFIG_DIR, "auto-push.sh");
export const LOG_PATH = join(CONFIG_DIR, "auto-push.log");
const PLIST_PATH = join(homedir(), "Library", "LaunchAgents", "com.tokenmax.push.plist");
const CRON_TAG = "# tokenmax auto-push";
const LABEL = "com.tokenmax.push";
/** Late enough that a day's work is in it, early enough to be before midnight. */
const HOUR = 21;

export type Scheduler = "launchd" | "cron";

export function schedulerFor(platform = process.platform): Scheduler | null {
  if (platform === "darwin") return "launchd";
  if (platform === "linux") return "cron";
  return null;
}

/** A tiny wrapper, so the schedule refers to one stable path rather than to
 *  whatever npx happened to resolve on the day it was installed. */
function writeScript(): void {
  if (!existsSync(CONFIG_DIR)) mkdirSync(CONFIG_DIR, { recursive: true, mode: 0o700 });
  writeFileSync(
    SCRIPT_PATH,
    [
      "#!/bin/sh",
      "# Generated by tokenmax. Remove with: tokenmax auto --off",
      `export TOKENMAX_API_URL="\${TOKENMAX_API_URL:-${INSTANCE_URL}}"`,
      `exec npx -y github:ultim8xyz/tokenmax-cli push >> "${LOG_PATH}" 2>&1`,
      "",
    ].join("\n"),
    { encoding: "utf-8", mode: 0o700 },
  );
}

function plist(): string {
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>${LABEL}</string>
  <key>ProgramArguments</key>
  <array><string>/bin/sh</string><string>${SCRIPT_PATH}</string></array>
  <key>StartCalendarInterval</key>
  <dict><key>Hour</key><integer>${HOUR}</integer><key>Minute</key><integer>0</integer></dict>
  <key>RunAtLoad</key><false/>
</dict>
</plist>
`;
}

function crontab(lines: string): void {
  execFileSync("crontab", ["-"], { input: lines, encoding: "utf-8" });
}

function readCrontab(): string {
  try {
    return execFileSync("crontab", ["-l"], { encoding: "utf-8", stdio: ["ignore", "pipe", "ignore"] });
  } catch {
    return "";
  }
}

export function isInstalled(): boolean {
  const scheduler = schedulerFor();
  if (scheduler === "launchd") return existsSync(PLIST_PATH);
  if (scheduler === "cron") return readCrontab().includes(CRON_TAG);
  return false;
}

/** Installs a daily push. Returns null when the platform has no scheduler. */
export function install(): Scheduler | null {
  const scheduler = schedulerFor();
  if (!scheduler) return null;
  writeScript();

  if (scheduler === "launchd") {
    mkdirSync(join(homedir(), "Library", "LaunchAgents"), { recursive: true });
    writeFileSync(PLIST_PATH, plist(), "utf-8");
    // Reloading is what makes a changed schedule take effect; a plain load on
    // an already-loaded label is a no-op that looks like success.
    try {
      execFileSync("launchctl", ["unload", PLIST_PATH], { stdio: "ignore" });
    } catch {
      // Not loaded yet, which is the normal first install.
    }
    execFileSync("launchctl", ["load", PLIST_PATH], { stdio: "ignore" });
    return "launchd";
  }

  const existing = readCrontab()
    .split("\n")
    .filter((l) => l && !l.includes(CRON_TAG));
  crontab([...existing, `0 ${HOUR} * * * /bin/sh ${SCRIPT_PATH} ${CRON_TAG}`, ""].join("\n"));
  return "cron";
}

export function uninstall(): void {
  const scheduler = schedulerFor();
  if (scheduler === "launchd" && existsSync(PLIST_PATH)) {
    try {
      execFileSync("launchctl", ["unload", PLIST_PATH], { stdio: "ignore" });
    } catch {
      // Already unloaded.
    }
    unlinkSync(PLIST_PATH);
  }
  if (scheduler === "cron") {
    const kept = readCrontab()
      .split("\n")
      .filter((l) => l && !l.includes(CRON_TAG));
    crontab([...kept, ""].join("\n"));
  }
  if (existsSync(SCRIPT_PATH)) unlinkSync(SCRIPT_PATH);
}
